# Generated by Django 5.1.2 on 2024-12-03 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 3, 9, 16, 49, 58068, tzinfo=datetime.timezone.utc)),
        ),
    ]
