# Generated by Django 5.1.2 on 2024-12-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.BooleanField(default=False),
        ),
    ]
