# Generated by Django 5.1.2 on 2024-12-04 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 5, 0, 9, 28, 50973)),
        ),
    ]
