# Generated by Django 5.1.2 on 2024-12-11 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_order_completed_alter_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='carousel_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carouselimage/')),
                ('heading', models.CharField(max_length=15)),
                ('Para', models.TextField(blank=True, default='', max_length=35, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 11, 15, 12, 18, 229349)),
        ),
    ]
