# Generated by Django 5.1.2 on 2025-02-07 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_carousel_img_carouselimg_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimg',
            name='Para',
            field=models.TextField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='carouselimg',
            name='heading',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='carouselimg',
            name='image',
            field=models.ImageField(upload_to='img/%y'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 7, 20, 55, 22, 808777)),
        ),
    ]
