# Generated by Django 5.1.2 on 2025-02-10 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_category_image_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimg',
            name='heading',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 10, 13, 56, 45, 642345)),
        ),
    ]
