# Generated by Django 5.1.2 on 2025-02-12 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_carouselimg_heading_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 2, 12, 13, 53, 20, 319649)),
        ),
    ]
